#!/usr/bin/env python3
"""
analysis.py

Post-processing and secondary analysis module for the
Network Pharmacology Analysis Pipeline.

This file:
- DOES NOT modify or rerun the pipeline
- Consumes CSV outputs generated by main.py
- Produces publication-ready statistics and figures

Author: Alex
License: MIT
"""

from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx


# ---------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------

DEFAULT_FIG_DPI = 300
TOP_N_HUBS = 15


# ---------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------

def ensure_dir(path: Path):
    """Create directory if it does not exist."""
    path.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------
# Network-level analyses
# ---------------------------------------------------------------------

def load_network_metrics(metrics_csv: Path) -> pd.DataFrame:
    """
    Load network metrics produced in Step 4.
    """
    df = pd.read_csv(metrics_csv)
    required_cols = {
        "Protein",
        "Degree",
        "Degree_Centrality",
        "Betweenness_Centrality",
        "Closeness_Centrality",
    }
    missing = required_cols - set(df.columns)
    if missing:
        raise ValueError(f"Missing required columns: {missing}")
    return df


def summarize_network_metrics(df: pd.DataFrame) -> pd.DataFrame:
    """
    Generate descriptive statistics for network metrics.
    """
    summary = df.drop(columns=["Protein"]).describe()
    return summary


def plot_degree_distribution(
    df: pd.DataFrame,
    output_path: Path,
):
    """
    Plot degree distribution of the PPI network.
    """
    plt.figure(figsize=(6, 4))
    plt.hist(df["Degree"], bins=20)
    plt.xlabel("Node degree")
    plt.ylabel("Frequency")
    plt.title("Degree distribution of PPI network")
    plt.tight_layout()
    plt.savefig(output_path, dpi=DEFAULT_FIG_DPI)
    plt.close()


def plot_top_hubs(
    df: pd.DataFrame,
    output_path: Path,
    top_n: int = TOP_N_HUBS,
):
    """
    Bar plot of top-N hub proteins by degree.
    """
    top_df = df.sort_values("Degree", ascending=False).head(top_n)

    plt.figure(figsize=(8, 4))
    plt.bar(top_df["Protein"], top_df["Degree"])
    plt.xticks(rotation=45, ha="right")
    plt.ylabel("Degree")
    plt.title(f"Top {top_n} hub proteins")
    plt.tight_layout()
    plt.savefig(output_path, dpi=DEFAULT_FIG_DPI)
    plt.close()


# ---------------------------------------------------------------------
# STRING interaction analysis
# ---------------------------------------------------------------------

def load_string_interactions(interactions_csv: Path) -> pd.DataFrame:
    """
    Load STRING interaction table.
    """
    df = pd.read_csv(interactions_csv)
    required_cols = {
        "preferredName_A",
        "preferredName_B",
        "score",
    }
    missing = required_cols - set(df.columns)
    if missing:
        raise ValueError(f"Missing required columns: {missing}")
    return df


def summarize_interaction_scores(df: pd.DataFrame) -> pd.Series:
    """
    Summary statistics for STRING confidence scores.
    """
    return df["score"].describe()


def plot_interaction_score_distribution(
    df: pd.DataFrame,
    output_path: Path,
):
    """
    Plot distribution of STRING confidence scores.
    """
    plt.figure(figsize=(6, 4))
    plt.hist(df["score"], bins=30)
    plt.xlabel("STRING confidence score")
    plt.ylabel("Frequency")
    plt.title("Distribution of STRING interaction confidence")
    plt.tight_layout()
    plt.savefig(output_path, dpi=DEFAULT_FIG_DPI)
    plt.close()


# ---------------------------------------------------------------------
# Enrichment analysis helpers
# ---------------------------------------------------------------------

def load_enrichment_table(csv_path: Path) -> pd.DataFrame:
    """
    Load enrichment results (GO, KEGG, Reactome).
    """
    df = pd.read_csv(csv_path)
    return df


def plot_top_enriched_terms(
    df: pd.DataFrame,
    output_path: Path,
    term_col: str,
    pval_col: str,
    top_n: int = 15,
    title: str = "",
):
    """
    Horizontal bar plot of top enriched terms by significance.
    """
    df = df.copy()
    df["-log10(p)"] = -np.log10(df[pval_col])
    top_df = df.sort_values(pval_col).head(top_n)

    plt.figure(figsize=(7, 5))
    plt.barh(top_df[term_col], top_df["-log10(p)"])
    plt.xlabel("-log10(p-value)")
    plt.title(title)
    plt.gca().invert_yaxis()
    plt.tight_layout()
    plt.savefig(output_path, dpi=DEFAULT_FIG_DPI)
    plt.close()


# ---------------------------------------------------------------------
# Main analysis workflow
# ---------------------------------------------------------------------

def run_analysis(output_dir: Path):
    """
    Run all post-hoc analyses.
    """
    analysis_dir = output_dir / "analysis"
    figures_dir = analysis_dir / "figures"
    tables_dir = analysis_dir / "tables"

    ensure_dir(figures_dir)
    ensure_dir(tables_dir)

    # ---------------------------
    # Network metrics
    # ---------------------------
    metrics_csv = output_dir / "step4_network" / "network_metrics.csv"
    metrics_df = load_network_metrics(metrics_csv)

    metrics_summary = summarize_network_metrics(metrics_df)
    metrics_summary.to_csv(tables_dir / "network_metrics_summary.csv")

    plot_degree_distribution(
        metrics_df,
        figures_dir / "degree_distribution.png",
    )

    plot_top_hubs(
        metrics_df,
        figures_dir / "top_hubs.png",
        top_n=TOP_N_HUBS,
    )

    # ---------------------------
    # STRING interactions
    # ---------------------------
    interactions_csv = output_dir / "step4_network" / "string_interactions.csv"
    interactions_df = load_string_interactions(interactions_csv)

    score_summary = summarize_interaction_scores(interactions_df)
    score_summary.to_csv(tables_dir / "string_score_summary.csv")

    plot_interaction_score_distribution(
        interactions_df,
        figures_dir / "string_score_distribution.png",
    )

    print("✓ analysis.py completed successfully")
    print(f"Results saved to: {analysis_dir}")


# ---------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Post-hoc analysis for network pharmacology pipeline"
    )
    parser.add_argument(
        "--output_dir",
        required=True,
        help="Pipeline output directory (compound_xxx_YYYYMMDD_HHMMSS)",
    )

    args = parser.parse_args()
    run_analysis(Path(args.output_dir))
